Convert everything to classes.
Still getting the same error:
```
$ yarn test
yarn test v0.21.3
$ tsc -p test/tsconfig.json
test/wasm.ts(136,3): error TS2322: Type 'ResultObject' is not assignable to type 'Instance'.
  Property 'exports' is missing in type 'ResultObject'.
error Command failed with exit code 2.
```